In [8]:
import pandas as pd

# load dataset
df = pd.read_csv(r"C:\Users\Mohammed Kaif\OneDrive\Desktop\Retail_Demand_KPI_Dashboard\online_retail.csv")

# preview
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6.0,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     537113 non-null  float64
 4   InvoiceDate  537113 non-null  object
 5   UnitPrice    537113 non-null  float64
 6   CustomerID   403722 non-null  float64
 7   Country      537113 non-null  object
dtypes: float64(3), object(5)
memory usage: 33.1+ MB

In [10]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity         4796
InvoiceDate      4796
UnitPrice        4796
CustomerID     138187
Country          4796
dtype: int64

In [11]:
df = df[df['Quantity'] > 0]

In [12]:
df = df.dropna(subset=['CustomerID'])

In [13]:
df = df.drop_duplicates()

In [14]:
remove_words = ['POSTAGE', 'DOTCOM POSTAGE', 'MANUAL', 'BANK CHARGES', 'CARRIAGE']

df = df[~df['Description'].isin(remove_words)]

In [15]:
df['Revenue'] = df['Quantity'] * df['UnitPrice']

In [16]:
df['Revenue'] = df['Revenue'].round(2)

In [17]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], dayfirst=True, errors='coerce')

In [18]:
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['Day'] = df['InvoiceDate'].dt.day

In [19]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 388483 entries, 0 to 541908
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    388483 non-null  object
 1   StockCode    388483 non-null  object
 2   Description  388483 non-null  object
 3   Quantity     388483 non-null  float64
 4   InvoiceDate  388483 non-null  datetime64[ns]
 5   UnitPrice    388483 non-null  float64
 6   CustomerID   388483 non-null  float64
 7   Country      388483 non-null  object
 8   Revenue      388483 non-null  float64
 9   Year         388483 non-null  int32
 10  Month        388483 non-null  int32
 11  Day          388483 non-null  int32
dtypes: datetime64[ns](1), float64(4), int32(3), object(4)
memory usage: 34.1+ MB

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,Day
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010,12,1
1,536365,71053,WHITE METAL LANTERN,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010,12,1
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1

In [20]:
import os

os.makedirs("data", exist_ok=True)

In [21]:
df.to_csv("data/cleaned_retail_data.csv", index=False)

In [22]:
df.to_csv("cleaned_retail_data.csv", index=False)

In [23]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
Revenue        0
Year           0
Month          0
Day            0
dtype: int64

In [24]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\mohammed kaif\appdata\local\programs\python\python312\lib\site-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in c:\users\mohammed kaif\appdata\local\programs\python\python312\lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in c:\users\mohammed kaif\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\mohammed kaif\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:YOUR_PASSWORD@localhost:5432/retail_demand_db"
)

In [26]:
engine = create_engine(
    "postgresql://postgres:60801787@localhost:5432/retail_demand_db"
)

In [27]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Revenue', 'Year', 'Month',
       'Day'],
      dtype='object')

In [28]:
df.to_sql(
    "retail_sales",
    engine,
    if_exists="replace",
    index=False
)

print("Data loaded successfully")

Data loaded successfully